const AccessControl = require("accesscontrol");
const ac = new AccessControl();

exports.roles = (function() {
ac.grant("supervisor")
 .readOwn("profile")
 .readAny("profile")
 .updateAny("profile")
 .updateOwn("profile")
 .readAny("company")
 .readAny("project")
 .updateAny("project")
 .create("project")
 .readAny("feature")
 .updateAny("feature")
 .create("feature")
 .readAny("task")
 .updateAny("task")
 .create("task")
 .readAny("investment")
 .updateAny("investment")
 .create("investment")
 .readAny("vendor")
 .updateAny("vendor")
 .create("vendor")
 .readAny("payment")
 .updateAny("payment")
 .create("payment")
 .readAny("return")
 .updateAny("return")
 .create("return")
 .readAny("investor")
 .updateAny("investor")
 .create("investor")
 .deleteAny("feature")
 .deleteAny("task")
 .create("profile")

ac.grant("admin")
 .extend("supervisor")
 .updateAny("company")
 .deleteAny("company")
 .create("company")
 .deleteAny("project")
 .deleteAny("investment")
 .deleteAny("vendor")
 .deleteAny("payment")
 .deleteAny("return")
 .deleteAny("investor")
 .deleteAny("profile")
ac.grant("super-admin")
 .extend("admin")
return ac;
})();
